name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild Expo Native Code
        run: npx expo prebuild --platform android

      - name: Make Gradle Executable
        run: chmod +x android/gradlew

      - name: Build APK with Gradle
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Release-APK
          path: android/app/build/outputs/apk/release/*.apk
